### PR TITLE
Expose `ember-cli:test` task

### PR DESCRIPTION
**Pull request by seanpdoyle**
Run `ember test` on each App, exit with status `1` if tests fail

Use case

```ruby
# Rakefile

require File.expand_path('../config/application', __FILE__)

MyApp::Application.load_tasks

task(:default).clear
task default: ["ember-cli:test", :spec]
```

### CODE REVIEW

**Comment by seanpdoyle** [comment]
Is there any opposition to this? 
If not I'd *love* to get this merged and pushed out to `npm`.

Right now, I'm pointing some things to this `github` and `branch` in my `Gemfile`, which is certainly a no-no.

cc: @rondale-sc @rwz

**Comment by rwz** [comment]
I'm sorry, I've actually kind of overlooked this PR.

**Comment by rwz** [comment]
Released 0.1.1

**Comment by rondale-sc** [comment]
+1

**Comment by seanpdoyle** [comment]
Awesome! thanks you two.

**Pull request merged**
