### PR TITLE
update ember-cli compatiblity versions, supporting through 1.13.x

### LINKED ISSUE #182: update EMBER_CLI_VERSION to use with ember-cli@1.13.0
Need up update at least this flag in order to use the updated ember-cli.

Changed the ember check and appears everything is working fine.

### PR DESCRIPTION
**Pull request by skylar**
fixes #182

### CODE REVIEW

**Comment by rzane** [comment]
This would break 0.2

**Comment by skylar** [comment]
thanks @rzane - i didn't quite understand the format. fixed.

**Comment by rzane** [comment]
Nice work!

**Comment by rwz** [comment]
https://github.com/rwz/ember-cli-rails/pull/180 beat you

**Comment by rwz** [comment]
Fixed and released 0.3.3

**Pull request closed without merging**
